/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    media: Media;
    pages: Page;
    navigation: Navigation;
    'site-settings': SiteSetting;
    redirects: Redirect;
    products: Product;
    services: Service;
    industries: Industry;
    projects: Project;
    resources: Resource;
    authors: Author;
    team: Team;
    testimonials: Testimonial;
    clients: Client;
    careers: Career;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  role: 'administrator' | 'publisher' | 'editor' | 'author';
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for accessibility. Describe what the image shows.
   */
  alt: string;
  caption?: string | null;
  /**
   * Internal assets must never be referenced by public pages.
   */
  classification: 'public' | 'internal';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment. Must be unique across all pages.
   */
  slug: string;
  seo: {
    /**
     * Shown in search results. Maximum 60 characters.
     */
    metaTitle: string;
    /**
     * Shown under the title in search results. Maximum 160 characters.
     */
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            variant: 'split' | 'centered' | 'minimal';
            /**
             * Short line shown above the heading.
             */
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            ctas?:
              | {
                  label: string;
                  url: string;
                  style: 'primary' | 'secondary';
                  id?: string | null;
                }[]
              | null;
            /**
             * Alternative text is inherited from the selected media record.
             */
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  /**
                   * Short label used to pick or render the icon.
                   */
                  iconLabel?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGroup';
          }
        | {
            items?:
              | {
                  label: string;
                  value: string;
                  /**
                   * Optional unit shown after the value, such as % or x.
                   */
                  suffix?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metricGroup';
          }
        | {
            items?:
              | {
                  quote: string;
                  authorName: string;
                  /**
                   * Role and company shown under the author name.
                   */
                  authorRole?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialGroup';
          }
        | {
            /**
             * Alternative text is inherited from the selected media record.
             */
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            /**
             * Pick at least two images. Alternative text is inherited from each media record.
             */
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            url: string;
            /**
             * Shown before playback. Alternative text is inherited from the selected media record.
             */
            poster?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
        | {
            headline?: string | null;
            product: number | Product;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            heading?: string | null;
            /**
             * Steps render in the order listed here.
             */
            steps: {
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            heading?: string | null;
            /**
             * Curated FAQs from the FAQ library. Used when at least one FAQ is selected.
             */
            faqs?: (number | Faq)[] | null;
            /**
             * One-off fallback questions rendered when no linked FAQs are selected.
             */
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            heading?: string | null;
            pages?: (number | Page)[] | null;
            products?: (number | Product)[] | null;
            services?: (number | Service)[] | null;
            projects?: (number | Project)[] | null;
            resources?: (number | Resource)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedContent';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Unique URL-safe identifier for this product.
   */
  slug: string;
  tagline?: string | null;
  heroImage?: (number | null) | Media;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  plans?:
    | {
        name: string;
        priceMonthly: number;
        /**
         * Three-letter uppercase ISO 4217 code, e.g. USD.
         */
        currency?: string | null;
        highlights?:
          | {
              highlight: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  relatedServices?: (number | Service)[] | null;
  relatedIndustries?: (number | Industry)[] | null;
  interfaceShowcase?:
    | {
        screenshot: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  seo: {
    /**
     * Recommended: up to 60 characters.
     */
    metaTitle: string;
    /**
     * Recommended: up to 160 characters.
     */
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Unique URL-safe identifier for this service.
   */
  slug: string;
  summary?: string | null;
  /**
   * Label of the icon used to represent this service.
   */
  icon?: string | null;
  overview: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  deliverables?:
    | {
        deliverable: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (number | Service)[] | null;
  relatedIndustries?: (number | Industry)[] | null;
  seo: {
    /**
     * Recommended: up to 60 characters.
     */
    metaTitle: string;
    /**
     * Recommended: up to 160 characters.
     */
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  /**
   * Unique URL-safe identifier for this industry.
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  heroImage?: (number | null) | Media;
  relatedServices?: (number | Service)[] | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    /**
     * Recommended: up to 60 characters.
     */
    metaTitle: string;
    /**
     * Recommended: up to 160 characters.
     */
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  /**
   * Sort position. Lower numbers first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Unique URL-safe identifier for this project.
   */
  slug: string;
  /**
   * Free-text client name to avoid coupling to the clients collection.
   */
  clientName?: string | null;
  industry?: (number | null) | Industry;
  servicesDelivered?: (number | Service)[] | null;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  approach?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outcome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  testimonialQuote?: string | null;
  testimonialAuthor?: string | null;
  seo: {
    /**
     * Recommended: up to 60 characters.
     */
    metaTitle: string;
    /**
     * Recommended: up to 160 characters.
     */
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * Unique URL-safe identifier for this resource.
   */
  slug: string;
  type: 'article' | 'guide' | 'whitepaper' | 'video';
  authors?: (number | Author)[] | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  publishedAt: string;
  seo: {
    /**
     * Recommended: up to 60 characters.
     */
    metaTitle: string;
    /**
     * Recommended: up to 160 characters.
     */
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  avatar?: (number | null) | Media;
  /**
   * Unique URL-safe identifier for this author.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items: {
    label: string;
    linkType?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    url?: string | null;
    children?:
      | {
          label: string;
          linkType?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  defaultOgImage?: (number | null) | Media;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Original path starting with a slash, e.g. /old-page.
   */
  fromPath: string;
  toUrl?: string | null;
  toPage?: (number | null) | Page;
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Unique URL-safe identifier for this team member.
   */
  slug: string;
  photo: number | Media;
  bio?: string | null;
  /**
   * Sort position on the team page. Lower numbers first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorRole?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Optional. Absolute URL including https://.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  /**
   * Unique URL-safe identifier for this opening.
   */
  slug: string;
  location?: string | null;
  employmentType: 'full-time' | 'part-time' | 'contract';
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  isOpen?: boolean | null;
  postedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'navigation';
        value: number | Navigation;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  classification?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        featureGroup?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    iconLabel?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metricGroup?:
          | T
          | {
              items?:
                | T
                | {
                    label?: T;
                    value?: T;
                    suffix?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialGroup?:
          | T
          | {
              items?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorRole?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              url?: T;
              poster?: T;
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              headline?: T;
              product?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              heading?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              heading?: T;
              faqs?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        relatedContent?:
          | T
          | {
              heading?: T;
              pages?: T;
              products?: T;
              services?: T;
              projects?: T;
              resources?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  defaultOgImage?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toUrl?: T;
  toPage?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  heroImage?: T;
  overview?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  plans?:
    | T
    | {
        name?: T;
        priceMonthly?: T;
        currency?: T;
        highlights?:
          | T
          | {
              highlight?: T;
              id?: T;
            };
        id?: T;
      };
  relatedProducts?: T;
  relatedServices?: T;
  relatedIndustries?: T;
  interfaceShowcase?:
    | T
    | {
        screenshot?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  overview?: T;
  deliverables?:
    | T
    | {
        deliverable?: T;
        id?: T;
      };
  relatedServices?: T;
  relatedIndustries?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  relatedServices?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  clientName?: T;
  industry?: T;
  servicesDelivered?: T;
  summary?: T;
  challenge?: T;
  approach?: T;
  outcome?: T;
  heroImage?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  testimonialQuote?: T;
  testimonialAuthor?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  authors?: T;
  body?: T;
  coverImage?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  slug?: T;
  photo?: T;
  bio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorRole?: T;
  company?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  employmentType?: T;
  description?: T;
  isOpen?: T;
  postedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}